# ------------------------------------
# Shutdown Daemon PowerShell Script
# Version 1.0.3
# -------------------------------------
param (
    [string] $ipAddress,
    [int] $port,
    [string] $secretKey
)

#--------------------------------------------------------------------------------
#                               Important
#
# This script reads information from a .env file located in $appDataPath
# If no .env file is present these values are default
# ipAddress = 0.0.0.0   - IP to bind the Daemon or as start parameter with -ipAddress
# port      = 8080      - Port to bind the Daemon or as start parameter with -port
# secretKey =           - Secret used to communicate with the Wake-on-LAN server, cannot be empty and must be set either in .env or as start parameter with -secretKey
#                         If not set via -secretKey or in .env prompt will come up to enter it.
#------------------------------------------------------------------------------


# -----------------------------
# Begin of Configuration Section
# Set your desired values here
# -----------------------------

$appDataPath = Join-Path -Path $env:APPDATA -ChildPath "shutdown-daemon"
# This creates the daemon's DATA folder named "shutdown-daemon".
# $env:APPDATA points to the user's AppData\Roaming directory.

$bcryptDllPath = Join-Path -Path $appDataPath -ChildPath "BCrypt.Net-Next.dll"
# This defines the path to the BCrypt.Net-Next.dll file, expected to be inside the "shutdown-daemon" folder.

$keyFile = Join-Path -Path $appDataPath -ChildPath "enc.bin"
# This sets the path to the encryption key file "enc.bin", located in the "shutdown-daemon" folder.

$usersFilePath = Join-Path -Path $appDataPath -ChildPath "users.json"
# This defines the path to the users file inside the "shutdown-daemon" folder,
# Used for storing user information in JSON format.

$logFilePath = Join-Path -Path $appDataPath -ChildPath "daemon.log"
# This creates the path for the log file named in the "shutdown-daemon" folder,
# where logging information for the daemon process can be stored.

$envFilePath = Join-Path -Path $appDataPath -ChildPath ".env"
# This constructs the full path to the ".env" file within the "shutdown-daemon" directory in the user's AppData folder.
# It combines the base path stored in $appDataPath with the ".env" file name.

$wolip = "100.125.20.111"
# This variable stores the IP address for Wake-on-LAN (WOL) server.
# It will be used to communicate with the Wake-on-LAN server.

$wolport = "8889"
# This defines the port number to used by the Wake-on-LAN server.

# -----------------------------
# End of Configuration Section
# Set your desired values here
# -----------------------------


# --------------------------------------------------------------------------------------
#                                  Main Script Logic
# Anything after this line will break functionality if you don't know what you're doing.
# ---------------------------------------------------------------------------------------

if (-not (Test-Path -Path $appDataPath)) {
    New-Item -ItemType Directory -Path $appDataPath -Force | Out-Null
}

$global:users = @{}

# Function to read a password without showing input
function Read-Password {

    # Display the prompt
    Write-Host -NoNewline "Enter Password: "

    $password = ""
    while ($true) {
        $key = [System.Console]::ReadKey($true)
        if ($key.Key -eq 'Enter') { break }
        if ($key.Key -eq 'Backspace' -and $password.Length -gt 0) {
            $password = $password.Substring(0, $password.Length - 1)
            [System.Console]::Write("`b `b")
        }
        elseif ($key.Key -ne 'Backspace') {
            $password += $key.KeyChar
            [System.Console]::Write('*')
        }
    }

    # Move to the next line after the password is entered
    Write-Host ""

    return $password
}

function Initialize-Users {
    if (-not (Test-Path -Path $appDataPath)) {
        New-Item -ItemType Directory -Path $appDataPath -Force | Out-Null
    }

    if (-not (Test-Path -Path $usersFilePath)) {
        Write-LogMessage "No users file found. Prompting user to set up the first username and password."

        $username = Read-Host "Enter username"
        #$password = Read-Host -AsSecureString "Enter password" | ConvertFrom-SecureString -AsPlainText
        $password = Read-Password
        $permission = Read-Host "Enter permission level (e.g., 'admin', 'user')"

        $hashedPassword = [BCrypt.Net.BCrypt]::HashPassword($password)

        $global:users = @{
            $username = @{
                "username"      = $username
                "password_hash" = $hashedPassword
                "permission"    = $permission
            }
        }

        $global:users | ConvertTo-Json -Depth 3 | Set-Content -Path $usersFilePath -Force

        Write-LogMessage "First user has been set up and saved successfully." White
    }
    else {
        Write-LogMessage "Loading existing users..." Cyan

        try {
            $global:users = Get-Content -Path $usersFilePath | ConvertFrom-Json
        }
        catch {
            Write-LogMessage "Error loading users from $($usersFilePath): $_"
            Exit
        }

        if ($null -eq $global:users) {
            Write-LogMessage "Failed to load users from $usersFilePath. Exiting."
            Exit
        }

        Write-LogMessage "Users loaded successfully." Cyan
    }
}

function Get-EnvValues {
    # Check if the .env file exists
    if (-not (Test-Path -Path $envFilePath)) {
        Write-Error "The specified .env file does not exist."
        return
    }

    # Create a hashtable to store the key-value pairs
    $envValues = @{}

    # Read the .env file line by line
    Get-Content $envFilePath | ForEach-Object {
        # Skip empty lines and lines that start with '#'
        if (-not ($_ -match '^\s*$') -and -not ($_ -match '^\s*#')) {
            # Split the line at the '=' character to extract key and value
            $key, $value = $_ -split '=', 2

            # Trim any whitespace and store the key-value pair in the hashtable
            $envValues[$key.Trim()] = $value.Trim()
        }
    }

    # Set default values for ipAddress, port, and secretKey if they are not set or are empty
    $ipAddress = if ($envValues['ipAddress']) { $envValues['ipAddress'] } else { "0.0.0.0" }   # Default to 0.0.0.0 or another value
    $port = if ($envValues['port']) { $envValues['port'] } else { "8080" }                      # Default to port 80 or another value
    $secretKey = if ($envValues['secretKey']) { $envValues['secretKey'] } else { "" }         # Default to an empty string

    # Return the values as an object
    return [pscustomobject]@{
        ipAddress = $ipAddress
        port      = $port
        secretKey = $secretKey
    }
}
$global:envData = Get-EnvValues

# Set default values for parameters if they are not provided
if (-not $PSBoundParameters.ContainsKey('ipAddress')) {
    $ipAddress = $global:envData.ipAddress
}

if (-not $PSBoundParameters.ContainsKey('port')) {
    $port = $global:envData.port
}

if (-not $PSBoundParameters.ContainsKey('secretKey')) {
    $secretKey = $global:envData.secretKey
}

if (-not $secretKey) {

    if ($PSCommandPath) {
        # Running as a .ps1 script
        $scriptName = Split-Path $PSCommandPath -Leaf
    }
    elseif ($MyInvocation.MyCommand.Path) {
        # Running as a compiled executable or script
        $scriptName = Split-Path $MyInvocation.MyCommand.Path -Leaf
    }
    elseif ([System.AppDomain]::CurrentDomain.FriendlyName) {
        # Use FriendlyName to get the executable name when running as a compiled executable
        $scriptName = [System.AppDomain]::CurrentDomain.FriendlyName
    }
    else {
        # Fallback for unknown cases
        $scriptName = "UnknownScript"
    }

    Write-Host "🔷 Please enter your secretKey as you did in wol_server.py.`n`   To skip this message Run : $scriptName -secretKey <yourkey>"
    $secretKey = Read-Host -Prompt "secrektKey"
    if (-not $secretKey) {
        Write-LogMessage "❌ Error: The secretKey parameter is required and was not provided." Red
        exit 1
    }
}

function Write-LogMessage {
    param (
        [string] $message,
        [string] $color = "red"
    )
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "$timestamp - $message"
    Add-Content -Path $logFilePath -Value $logMessage
    Write-Host $logMessage -ForegroundColor $color
}
function Restore-BcryptDll {
    if (-not (Test-Path $bcryptDllPath)) {
        Write-LogMessage "BCrypt.Net DLL not found, extracting from script..."

        # Base64-encoded BCrypt.Net DLL string (Please DO NOT DELETE THIS LINES)
        $base64Dll = @"
        TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAHpItl8AAAAAAAAAAOAAIiALATAAAFoAAAAKAAAAAAAAamUAAAAgAAAAgAAAAAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAADAAAAAAgAAJX4AAAMAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAABVlAABPAAAAAIAAAIgGAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAwAAACwVQAAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAUFgAAAAgAAAAWgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAIgGAAAAgAAAAAgAAABcAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAKAAAAACAAAAZAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAABJZQAAAAAAAEgAAAACAAUArDAAAIQkAAAJAAAAAAAAAAAAAAAAAAAAMFUAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMwCQAQAAAAAAAAAAIDFhUEFhUFDgQoAgAABioTMAQAAAEAAAEAABECLQtyAQAAcHMPAAAKegMoEAAACiwQchcAAHByMQAAcHMRAAAKegIDBAUoEgAABjnBAAAAAxZvEgAACh8kMwsDF28SAAAKHzIuC3JJAABwczcAAAZ6AxhvEgAACh8kMwQZCis0AxhvEgAACgwIH2EuDwgfYi4KCB94LgUIH3kzCwMZbxIAAAofJC4LcncAAHBzNwAABnoaCgMGGFhvEgAACh8kMQtypwAAcHM3AAAGegMGGG8TAAAKKBQAAAoLDgcXMgYOBx8fMQtyzwAAcHM3AAAGeg4ILQgHDgcxAwcQBw4EDgcfYSgNAAAGDgUOBigLAAAGKnIBAQBwcyAAAAZ6PgIDH2EoDQAABigKAAAGKjICKBAAAAYoCgAABio6AigQAAAGFxcoCwAABipGAgMfYSgNAAAGFxcoCwAABipGAgMfYSgNAAAGFwQoCwAABipGAgQfYSgNAAAGFwMoCwAABipGAgMfYSgNAAAGBBcoCwAABioqAgMWFygLAAAGKgATMAQAtAEAAAIAABECLQtyXwEAcHMPAAAKegMoEAAACiwQcnEBAHByxwEAcHMRAAAKegQsFAUVMxBy0QEAcHK4AgBwcxEAAAp6FgsDFm8SAAAKHyQzCwMXbxIAAAofMi4LcsoCAHBzNwAABnoDGG8SAAAKHyQzBBkKKzQDGG8SAAAKCwcfYS4PBx9iLgoHH3guBQcfeTMLAxlvEgAACh8kLgty9AIAcHM3AAAGehoKAwYYWG8SAAAKHyQxC3IgAwBwczcAAAZ6AwYYbxMAAAooFAAACgwIFzIFCB8fMQtySAMAcHM3AAAGegMGGVgfFm8TAAAKDQQsFn4DAAAEAm8VAAAKBwUoDAAABhMEKyN+AwAABAIHH2EvB3J6AwBwKwVyfAMAcCgWAAAKbxUAAAoTBAkfECgVAAAGEwVzHQAABhMGEQYRBBEFCG8cAAAGEwcfPHMXAAAKEwgRCHKAAwBwbxgAAAoHbxkAAAofJG8ZAAAKEgJyhgMAcCgaAAAKbxgAAAofJG8ZAAAKJhEIEQURBY5pKBQAAAZvGwAACiYRCBEHfgkAAASOaRpaF1koFAAABm8bAAAKJhEIbxwAAAoqGzAEAO4AAAADAAARBEUDAAAABQAAAEgAAACIAAAAOMMAAAAoHQAACgp+AwAABAYCbx4AAAooHwAACgMfYS8HcnoDAHArBXJ8AwBwKBYAAApvFQAAChAA3ZwAAAAGLAYGbyAAAArcKCEAAAoLfgMAAAQHAm8eAAAKKB8AAAoDH2EvB3J6AwBwKwVyfAMAcCgWAAAKbxUAAAoQAN5cBywGB28gAAAK3CgiAAAKDH4DAAAECAJvHgAACigfAAAKAx9hLwdyegMAcCsFcnwDAHAoFgAACm8VAAAKEADeHAgsBghvIAAACtxyuAIAcASMBwAAAhRzIwAACnoCKgAAASgAAAIAHQAzUAAKAAAAAAIAYAAwkAAKAAAAAAIAoAAw0AAKAAAAABMwBQC4AAAABAAAEQIaMgUCHx8xKHKMAwBwAoweAAABcqIDAHAajCIAAAEfH4wiAAABKCQAAApzIwAACnoDH2EuHwMfYi4aAx94LhUDH3kuEHISBABwcmAEAHBzEQAACnofEI0jAAABCn4GAAAEBm8lAAAKHx1zFwAACgsHcoADAHBvGAAACgNvGQAACh8kbxkAAAoPAHKGAwBwKBoAAApvGAAACh8kbxkAAAomBwYGjmkoFAAABm8bAAAKJgdvHAAACioTMAIADAAAAAUAABECKC8AAAYKBgP+BCobMAIAGAAAAAYAABECKC4AAAYK3g0LcogEAHAHcy0AAAZ6BioBEAAAAAAAAAkJAA0WAAABKh8LH2EoDQAABioqAgMXBCgSAAAGKpJ+AwAABANvFQAACn4DAAAEAgMEBSgLAAAGbxUAAAooEwAABioAEzAEADcAAAAHAAARAi0FAy0CFyoCLAsDLAgCjmkDjmkuAhYqFgoWCysOBgIHkQMHkWFgCgcXWAsHAo5pMuwGFv4BKgATMAUAIgEAAAgAABEDFjEGAwKOaTEQctAEAHBy7gQAcHMRAAAKegNsIwAAAAAAABBAWiMAAAAAAAAIQFsoJgAACmkKBo0lAAABCxYMFg040gAAAAIJJRdYDZEg/wAAAF8TBAcIJRdYDH4KAAAEEQQYYx8/X5OdEQQZXxpiEwQJAzIXBwglF1gMfgoAAAQRBB8/X5OdOJMAAAACCSUXWA2RIP8AAABfEwURBBEFGmMfD19gEwQHCCUXWAx+CgAABBEEHz9fk50RBR8PXxhiEwQJAzIUBwglF1gMfgoAAAQRBB8/X5OdK0UCCSUXWA2RIP8AAABfEwURBBEFHGMZX2ATBAcIJRdYDH4KAAAEEQQfP1+TnQcIJRdYDH4KAAAEEQUfP1+TnQkDPyf///8HKgAAEzAFAOMAAAAJAAARAm8nAAAKChYLAxYwEHL8BABwcjQFAHBzEQAACnoDjSMAAAEMFg04qQAAAAIJJRdYDW8SAAAKKBYAAAYTBAIJJRdYDW8SAAAKKBYAAAYTBREEFTuKAAAAEQUVO4IAAAAIBxEEGGIRBR8wXxpjYNKcBxdYJQsDL2oJBi9mAgklF1gNbxIAAAooFgAABhMGEQYVLk8IBxEFHw9fGmIRBh88XxhjYNKcBxdYJQsDLzQJBi8wAgklF1gNbxIAAAooFgAABhMHCAcRBhlfHGIRB2DSnAcXWAsJBhdZLwcHAz9K////CCpiAhYyEgJ+CwAABI5pMAh+CwAABAKUKhUqEzAFABMBAAAKAAARAwSVCgMEF1iVCwYCexEAAAQWlWEKFgw42gAAAAJ7EgAABAYfGGQg/wAAAF+VDQkCexIAAAQgAAEAAAYfEGQg/wAAAF9glVgNCQJ7EgAABCAAAgAABh5kIP8AAABfYJVhDQkCexIAAAQgAAMAAAYg/wAAAF9glVgNBwkCexEAAAQIF1glDJVhYQsCexIAAAQHHxhkIP8AAABflQ0JAnsSAAAEIAABAAAHHxBkIP8AAABfYJVYDQkCexIAAAQgAAIAAAceZCD/AAAAX2CVYQ0JAnsSAAAEIAADAAAHIP8AAABfYJVYDQYJAnsRAAAECBdYJQyVYWEKCB8OQx7///8DBAcCexEAAAQfEZVhngMEF1gGnioAEzADACkAAAALAAARFgsWCisdBx5iAgNKkSD/AAAAX2ALAwNKF1gCjmldVAYXWAoGGjLfByoAAAATMAMAUwAAAAAAAAACfgcAAASOaY0mAAABfREAAAQCfggAAASOaY0mAAABfRIAAAR+BwAABAJ7EQAABH4HAAAEjmkoKAAACn4IAAAEAnsSAAAEfggAAASOaSgoAAAKKgATMAUAmwAAAAwAABEWCxiNJgAAAQwCexEAAASOaQ0CexIAAASOaRMEFgorHQJ7EQAABAYCexEAAAQGlQMSASgYAAAGYZ4GF1gKBgky3xYKKyQCCBYoFwAABgJ7EQAABAYIFpWeAnsRAAAEBhdYCBeVngYYWAoGCTLYFgorJAIIFigXAAAGAnsSAAAEBggWlZ4CexIAAAQGF1gIF5WeBhhYCgYRBDLXKgATMAUA7AAAAA0AABEWCxYMGI0mAAABDQJ7EQAABI5pEwQCexIAAASOaRMFFgorHQJ7EQAABAYCexEAAAQGlQQSASgYAAAGYZ4GF1gKBhEEMt4WCitKCRaPJgAAASVLAxICKBgAAAZhVAkXjyYAAAElSwMSAigYAAAGYVQCCRYoFwAABgJ7EQAABAYJFpWeAnsRAAAEBhdYCReVngYYWAoGEQQysRYKK0oJFo8mAAABJUsDEgIoGAAABmFUCRePJgAAASVLAxICKBgAAAZhVAIJFigXAAAGAnsSAAAEBgkWlZ4CexIAAAQGF1gJF5WeBhhYCgYRBTKxKhMwBAArAQAADgAAEX4JAAAEjmmNJgAAAQx+CQAABAh+CQAABI5pKCgAAAoIjmkNBRoyBQUfHzEQck4FAHByjAMAcHMRAAAKegSOaR8QLhByeAUAcHKYBQBwcxEAAAp6FwUfH19iEwQRBBc0EHJOBQBwcowDAHBzEQAACnoCKBkAAAYCBAMoGwAABhYKKxICAygaAAAGAgQoGgAABgYXWAoGahEEbjPnFgorHBYLKw4CCAcXYigXAAAGBxdYCwcJF2My7AYXWAoGH0Ay3wkaWo0jAAABEwUWChYLK1QRBQclF1gLCAaVHxhkIP8AAABf0pwRBQclF1gLCAaVHxBkIP8AAABf0pwRBQclF1gLCAaVHmQg/wAAAF/SnBEFByUXWAsIBpUg/wAAAF/SnAYXWAoGCTKoEQUqHgIoKQAACioAEzADAI8AAAAAAAAAFhdzKgAACoADAAAEKCsAAAqABgAABB8SjSYAAAEl0CIAAAQoLAAACoAHAAAEIAAEAACNJgAAASXQHgAABCgsAAAKgAgAAAQcjSYAAAEl0CEAAAQoLAAACoAJAAAEH0CNJQAAASXQIAAABCgsAAAKgAoAAAQggAAAAI0eAAABJdAfAAAEKCwAAAqACwAABCoeAigtAAAKKiICAyguAAAKKiYCAwQoLwAACiqSAigpAAAKAgMoJAAABgIEKCYAAAYCBSgoAAAGAg4EKCoAAAYqHgJ7EwAABCoiAgN9EwAABCoeAnsUAAAEKiICA30UAAAEKh4CexUAAAQqIgIDfRUAAAQqHgJ7FgAABCoiAgN9FgAABCoAEzAFAEgAAAAPAAARAhIAKDAAAAYtBSg0AAAGAhYGbzwAAAZvEwAACgIXBm86AAAGbxMAAAoCBm87AAAGGG8TAAAKAgZvPQAABm8wAAAKcyIAAAYqEzAEADEAAAAQAAARAhIAKDAAAAYtBSg0AAAGBm87AAAGCx8KAgdvEgAACh8wWVoCBxdYbxIAAAofMFlYKgAAABMwBADUAAAABwAAEQItC3KsBQBwcw8AAAp6Am8nAAAKHzsuDwJvJwAACh88LgUDFFEWKgJygAMAcG8xAAAKLQUDFFEWKhgKAgZvEgAACigxAAAGLA0GF1gKA34YAAAEUSsHA34XAAAEUQIGJRdYCm8SAAAKHyQuBQMUURYqAgYlF1gKbxIAAAooMwAABiwSAgYlF1gKbxIAAAooMwAABi0FAxRRFioCBiUXWApvEgAACh8kLgUDFFEWKgYLKxcCB28SAAAKKDIAAAYtBQMUURYqBxdYCwcCbycAAAoy4BcqXgIfYS4QAh9iLgsCH3guBgIfef4BKhcqwgIfLi4pAh8vLiQCHzAyBQIfOTEaAh9BMgUCH1oxEAIfYTIJAh96/gIW/gEqFioXKkICHzAyCQIfOf4CFv4BKhYqLnK2BQBwczcAAAZ6XhdzOQAABoAXAAAEGHM5AAAGgBgAAAQq6gIoKQAACgIDfSMAAAQCFwIoOgAABlgXWH0kAAAEAgIoOwAABhhYfSUAAAQCAig8AAAGF1h9JgAABCoeAnsjAAAEKh4CeyQAAAQqHgJ7JQAABCoeAnsmAAAEKgAAAEJTSkIBAAEAAAAAAAwAAAB2NC4wLjMwMzE5AAAAAAUAbAAAAFgMAAAjfgAAxAwAAPALAAAjU3RyaW5ncwAAAAC0GAAA4AUAACNVUwCUHgAAEAAAACNHVUlEAAAApB4AAOAFAAAjQmxvYgAAAAAAAAACAAABV52iIQkCAAAA+gEzABYAAAEAAAAqAAAADwAAACYAAAA9AAAAXAAAADEAAAAbAAAAIgAAAAUAAAAQAAAAAgAAAAgAAAAMAAAABQAAAAEAAAABAAAABgAAAAAAEwcBAAAAAAAGADIFtAkGAJ8FtAkGAF0EbQkPANQJAAAGAJoE6QUGAIYFrQcGAPYErQcGAGsFrQcGABUFrQcGALMErQcGANAErQcGAFIFrQcGAHEErQcGAIUKKwcGANgF8woGAMMIfgsGAIgEKwcGAJcI8woGAOQBfgsGABIBfgsGAGAAfgsGAFIIKwcGAEIEtAkGAEAHKwcGAPADKwcGAO4HKwcGADkGKwcGAEoIKwcGANsKKwcGAGgAKwcGADIHfgsGAMwDKwcGAL8HKwcGAN4BKwcGAL0FKwcGAL8GKwcGAJIIKwcGAGcAKwcGADkLKwcGANQF8woGAFEKtAkGANgDKwcAAAAAMQIAAAAAAQABAAEBEADUCowKOQABAAEAASAQAAQIjApZABMAHwABARAAnQeMCjkAEwAiAAEhEAAiCIwKWQAXACsAgAEQAK4IjAo5ABcALgABAQAAIQSMCmEAGQA2AAEAEADbB4wKWQAeADYAAAEAADoCAAA5AB4AOQADABAAQQkAADkAIwA5ABMBAADMAAAAZQAnAD4AEwEAAG4AAABlACcAPgATAQAACgIAAGUAJwA+ABMBAABCAAAAZQAnAD4AEwEAAOsBAABlACcAPgBRgJwJGwJRgEUHGwIxACgCHgJRgPoDIgJRgIAJGwIxAF8IJgIxAMgFKgIxAM4FKgIxAP8KKgIxALkDLgIxAAoBMgJRgDQGNgJRgH8HOQJRgCcHNgJRgJIJPAJRgKoJPAIBAFwIKgIBAGoJKgIBAB0DNgIBAOgCNgIBAAEDNgIBAJECNgIxAC0JPwIxAFYJPwIGBlkCGwJWgOsDIgJWgOQBIgJWgBIBIgJWgGAAIgIzAZsBQwIzAYsARwIzARkBSwIzAVoBTwIzAQEAUwIhAMkCGwIhAFMDGwIhAKoCGwIhADcDGwJQIAAAAACWAIkDVwIBAGwgAAAAAJYAiQNgAgYAeCEAAAAAlgAgBm8CDwCIIQAAAACWAKwDdQIRAJUhAAAAAJYApAN1AhIApCEAAAAAlgCkA28CEwC2IQAAAACWAKQDegIVAMghAAAAAJYApAOCAhgA2iEAAAAAlgCsA4oCGwDsIQAAAACWAKwDTQAeAPghAAAAAJYArAORAiAAuCMAAAAAkQBKBpoCJADcJAAAAACWAMIKpAInAKAlAAAAAJYAqwaqAikAuCUAAAAAlgBjBrACKwDsJQAAAACWAMIKtgIsAPclAAAAAJYAbwu6AiwAAiYAAAAAlgB3C8ICLwAoJgAASACRADoKywIzAGwmAAAAAJEA9gDTAjUAnCcAAAAAkwDpANsCNwCLKAAAAACRAAMB4gI5AKQoAAAAAIEApQjnAjoAxCkAAAAAkQB8A+4CPAD8KQAAAACBAEYLBgA+AFwqAAAAAIEAawupAD4ABCsAAAAAgQA/C/YCPwD8KwAAAACDABEL/gJBADMtAAAAAIYY2QgGAEQAPC0AAAAAkRgmCQgDRADXLQAAAACGGNkIBgBEAN8tAAAAAIYY2QgQAEQA6C0AAAAAhhjZCCgBRQDyLQAAAACDGNkIDANHABcuAAAAAIYIFwprAEsAHy4AAAAAgQgkChAASwAoLgAAAACGCGcHawBMADAuAAAAAIEIcwcQAEwAOS4AAAAAhgjfCGsATQBBLgAAAACBCO4IEABNAEouAAAAAIYIiwZrAE4AUi4AAAAAgQiXBhAATgDXLQAAAACGGNkIBgBPAN8tAAAAAIYY2QgQAE8A6C0AAAAAhhjZCCgBUABcLgAAAACWAJoHsAJSALAuAAAAAJYADQkUA1MA8C4AAAAAkQBXBhkDVADQLwAAAACRAH4IIQNWAOgvAAAAAJEAZgghA1cAGTAAAAAAkQBvAiEDWAAqMAAAAACRAGcKCANZADYwAAAAAJEYJgkIA1kA1y0AAAAAhhjZCAYAWQDfLQAAAACGGNkIEABZAOgtAAAAAIYY2QgoAVoATjAAAAAAhhjZCAEAXACJMAAAAACGCOEG2gBdAJEwAAAAAIYIpgraAF0AmTAAAAAAhgjPBtoAXQChMAAAAACGCJcK2gBdAAAAAQBUCwAAAgB/BgAAAwBoCxAQBAAbCRAQBQD9CAAAAQBUCwAAAgB/BgAAAwCgCwAABAASBAAABQBoCxAQBgC6CxAQBwAeBBAQCAAbCRAQCQD9CAAAAQBfCxAQAgAbCQAAAQBfCwAAAQBfCwAAAQBfCwAAAgAbCQAAAQBfCwAAAgAbCQAAAwAqBAAAAQBfCwAAAgAqBBAQAwAbCQAAAQBfCwAAAgAbCRAQAwDQCwAAAQBfCwAAAgDPCgAAAQBfCwAAAgDPCgAAAwDQCxAQBAAqBAAAAQADCgAAAgBTBwAAAwAqBAAAAQAbCRAQAgBTBwAAAQC6BgAAAgB+AgAAAQC6BgAAAQAMCwAAAgC6BhAQAwAqBAAAAQAMCwAAAgC6BhAQAwDQCxAQBAAqBAAAAQBkAgAAAgBtAgAAAQAaCwAAAgABBwAAAQASBgAAAgDjCQAAAQC5CAAAAQA0CwAAAgC7CgAAAQBhAgAAAgC7CgAAAQAOCgAAAQD5CQAAAgADCgAAAQADCgAAAgD5CQAAAwAbCQAAAQDEAwAAAQDEAwAAAgA7CAAAAQAxCgAAAgCSBwAAAwAbCQAABACjBgAAAQDCBQAAAQDCBQAAAQDCBQAAAQDCBQAAAQDEAwAAAQDEAwAAAgA7CAAAAQC6BgAAAQC6BgAAAQC6BgIAAgB+CgAAAQDCBQAAAQDCBQAAAQDCBQAAAQDEAwAAAQDEAwAAAgA7CAAAAQDzBgkA2QgBABEA2QgGABkA2QgKACkA2QgQADEA2QgQADkA2QgQAEEA2QgQAEkA2QgQAFEA2QgQAFkA2QgQAGEA2QgQAGkA2QgQAIkA2QgQALkA2QgGANEA2QgQANkA4AsbAOEA2QggANkARwomANkAQAYrAOkA3AExAHkA8AlHANkAYApNAJEA2QgBAJEAdQNTAJEAdQNZAPEAKwZfAJEAdQNkAHEAKwZrAJkAOwR4APkAcwZ9AOkAAwaEAAEBMwQGAKEAOwSKAKkAOwSPAAkB2QiUANkAdwqiAIEA8AmpACEB4QXJANkAxAbaADkBmwvqAHEA2QgGAEEB2QgTAYEAOwQZAUkBJAseAbEA2QgGALEA2QgQALEA2QgoAdkAQAY0AdkACAc/AQgABADvAQgACAD0AQgAEAD5AQgAEQDvAQgAFAD0AQIAFQAZAgIALQAZAg4AMAAAAAgAMQD5AQMANAD+AQgANQDvAQ4AOAABAgIAOQAZAgYAPAAEAgYAQAAHAggAQQDvAQgAaAAKAggAaQDvAQgAbAAPAggAcAD5AQgAdAAUAgIAdQAZAggAjQD5AQMAoQD+AQgAuQD5AQIAxQAZAggAyQD5AS4ACwAuAy4AEwA3Ay4AGwBWAy4AIwBfAy4AKwCnAy4AMwDWAy4AOwDjAy4AQwAcBC4ASwBlBS4AUwByBS4AWwB9BS4AYwB9BWAAawCSBSMBcwD5AWECcwD5AYECcwD5AaECcwD5AcECcwD5AWAEcwD5AWEEcwD5AYAEcwD5AYEEcwD5AaAEcwD5AaEEcwD5AcAEcwD5AcEEcwD5AeAEcwD5AQAFcwD5ASAFcwD5AUAFcwD5AUAHcwD5AWAHcwD5AYAHcwD5AaAHcwD5AQEAGAAAAAsAAQBIAAAADAABAIAAAAANAAEAAAIAAA4AAQAAEAAADwAVADYAbwCbAK8AswC6AL8AzgDeAOUA9QD+AAgBLwE5AQQAAQAKAAUAAAAoCiYDAACKByYDAAAQCSYDAACbBiYDAADlBioDAACqCioDAADTBioDAACbCioDAgAjAAMAAQAkAAMAAgAlAAUAAQAmAAUAAgAnAAcAAQAoAAcAAgApAAkAAQAqAAkAAgA6AAsAAgA7AA0AAgA8AA8AAgA9ABEAcGUAAB4AcHUAAB8AcHcAACAA8HcAACEACHgAACIABIAAAAQAAAACAAAAAQAAAE0B4woAAAQAAAAAAAAAAAAAAEQBZgIAAAAACgAGAAsACQAMAAkADQAJAA4ACQAPAAkAAAAARkExQUQyNzBCMjNCQTY0MEU4OEVFN0Y1MUNDOUMwQzFBNkM2QkIxRjJCOTAyNTY4MkE3RDMwRkIzQkRBNjRGMABfX1N0YXRpY0FycmF5SW5pdFR5cGVTaXplPTUxMgBTSEE1MTIAVUludDMyAF9fU3RhdGljQXJyYXlJbml0VHlwZVNpemU9NzIANzIyQTkzMUY0N0NERTU4QUExRUNFNEYzOEVEQjVGRkUwM0FBMTVGNUQ0QzVDQjY2NDExQTEyNzA4NDBEMkZBMgBfX1N0YXRpY0FycmF5SW5pdFR5cGVTaXplPTI0AERlY29kZUJhc2U2NABFbmNvZGVCYXNlNjQAQ2hhcjY0AEluZGV4NjQAU0hBMzg0ADc2RjIxMjUxMDREMTEzREEwMTEyMUZFMEMxNjE5RjI4NjFERTlFRTA1QUJBNUMyODk3MDg3RUI0MDMxMDAzNjUAREMxQ0RFRDYyMDRERjcwQUM1QzY0RUQyQzk5NThGRTc1NDc5NDAwRkUxRTFBODBGNzdDM0E1QkM2RkZBRjBBNQAzMkQwOEEwOEYxRTBCNzlBOTk0RUQ5MDNDMzZBNzk1NkUzNkYxQzk5RDY4RkRCNjc0NjBBQ0FBQzgzQ0E5QzA2AFRvSW50MTYAU0hBMjU2AF9fU3RhdGljQXJyYXlJbml0VHlwZVNpemU9NDA5NgBfX1N0YXRpY0FycmF5SW5pdFR5cGVTaXplPTEyOABTYWZlVVRGOAA8TW9kdWxlPgA8UHJpdmF0ZUltcGxlbWVudGF0aW9uRGV0YWlscz4AdmFsdWVfXwBkYXRhAG1zY29ybGliAElzQXNjaWlOdW1lcmljAG5ld01pbmltdW1Xb3JrTG9hZAA8UmF3SGFzaD5rX19CYWNraW5nRmllbGQAPFNldHRpbmdMZW5ndGg+a19fQmFja2luZ0ZpZWxkADxWZXJzaW9uTGVuZ3RoPmtfX0JhY2tpbmdGaWVsZAA8VmVyc2lvbj5rX19CYWNraW5nRmllbGQAPFdvcmtGYWN0b3I+a19fQmFja2luZ0ZpZWxkADxTZXR0aW5ncz5rX19CYWNraW5nRmllbGQAPEhhc2hPZmZzZXQ+a19fQmFja2luZ0ZpZWxkADxXb3JrZmFjdG9yT2Zmc2V0PmtfX0JhY2tpbmdGaWVsZABBcHBlbmQAU3RyZWFtVG9Xb3JkAFZhbGlkYXRlQW5kUmVwbGFjZVBhc3N3b3JkAEVuaGFuY2VkSGFzaFBhc3N3b3JkAEJhc2U2NENvZGUAbWVzc2FnZQBJRGlzcG9zYWJsZQBSdW50aW1lRmllbGRIYW5kbGUATm9uZQBWYWx1ZVR5cGUARGVmYXVsdEVuaGFuY2VkSGFzaFR5cGUAb2xkSGFzaFR5cGUAbmV3SGFzaFR5cGUAaGFzaFR5cGUARGlzcG9zZQBDcmVhdGUAQ29tcGlsZXJHZW5lcmF0ZWRBdHRyaWJ1dGUARGVidWdnYWJsZUF0dHJpYnV0ZQBBc3NlbWJseVRpdGxlQXR0cmlidXRlAE9ic29sZXRlQXR0cmlidXRlAFRhcmdldEZyYW1ld29ya0F0dHJpYnV0ZQBBc3NlbWJseUZpbGVWZXJzaW9uQXR0cmlidXRlAEFzc2VtYmx5SW5mb3JtYXRpb25hbFZlcnNpb25BdHRyaWJ1dGUAQXNzZW1ibHlDb25maWd1cmF0aW9uQXR0cmlidXRlAEFzc2VtYmx5RGVzY3JpcHRpb25BdHRyaWJ1dGUAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJpYnV0ZQBBc3NlbWJseVByb2R1Y3RBdHRyaWJ1dGUAQXNzZW1ibHlDb3B5cmlnaHRBdHRyaWJ1dGUAQXNzZW1ibHlDb21wYW55QXR0cmlidXRlAFJ1bnRpbWVDb21wYXRpYmlsaXR5QXR0cmlidXRlAEJ5dGUAdmFsdWUAUE9yaWcAU09yaWcAVVRGOEVuY29kaW5nAENlaWxpbmcAU3lzdGVtLlJ1bnRpbWUuVmVyc2lvbmluZwBUb0Jhc2U2NFN0cmluZwBlbmNvZGVkU3RyaW5nAEhhc2hTdHJpbmcAVG9TdHJpbmcARW1wdHlTdHJpbmcAU3Vic3RyaW5nAEVuaGFuY2VkSGFzaABJc1ZhbGlkSGFzaABJbnRlcnJvZ2F0ZUhhc2gAQ29tcHV0ZUhhc2gAY3VycmVudEhhc2gAZ2V0X1Jhd0hhc2gAc2V0X1Jhd0hhc2gAcmF3SGFzaABQYXNzd29yZE5lZWRzUmVoYXNoAE1hdGgAZ2V0X0xlbmd0aABnZXRfU2V0dGluZ0xlbmd0aABnZXRfVmVyc2lvbkxlbmd0aAB2ZXJzaW9uTGVuZ3RoAGxlbmd0aABTdGFydHNXaXRoAEJDcnlwdC5OZXQtTmV4dC5kbGwATnVsAFN5c3RlbQBIYXNoQWxnb3JpdGhtAEVudW0AQkNyeXB0U2FsdExlbgBiY3J5cHRNaW5vclJldmlzaW9uAGdldF9WZXJzaW9uAHNldF9WZXJzaW9uAERlZmF1bHRIYXNoVmVyc2lvbgB2ZXJzaW9uAEdldEhhc2hJbmZvcm1hdGlvbgBTeXN0ZW0uUmVmbGVjdGlvbgBBcmd1bWVudE91dE9mUmFuZ2VFeGNlcHRpb24AU2FsdFBhcnNlRXhjZXB0aW9uAEFyZ3VtZW50TnVsbEV4Y2VwdGlvbgBCY3J5cHRBdXRoZW50aWNhdGlvbkV4Y2VwdGlvbgBIYXNoSW5mb3JtYXRpb25FeGNlcHRpb24AaW5uZXJFeGNlcHRpb24AQXJndW1lbnRFeGNlcHRpb24AX3AAUm5nQ3NwAElzVmFsaWRCQ3J5cHRCYXNlNjRDaGFyAElzVmFsaWRCQ3J5cHRWZXJzaW9uQ2hhcgBTdHJpbmdCdWlsZGVyAEVuY2lwaGVyAEhhc2hQYXJzZXIAY2hhcmFjdGVyAFJhbmRvbU51bWJlckdlbmVyYXRvcgAuY3RvcgBnZXRfV29ya0ZhY3RvcgBzZXRfV29ya0ZhY3RvcgBmb3JjZVdvcmtGYWN0b3IAR2V0V29ya0ZhY3RvcgB3b3JrRmFjdG9yAC5jY3RvcgBPbGRGb3JtYXREZXNjcmlwdG9yAEhhc2hGb3JtYXREZXNjcmlwdG9yAE5ld0Zvcm1hdERlc2NyaXB0b3IAX3MAU3lzdGVtLkRpYWdub3N0aWNzAEJsb3dmaXNoTnVtUm91bmRzAE1pblJvdW5kcwBEZWZhdWx0Um91bmRzAE1heFJvdW5kcwBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzAERlYnVnZ2luZ01vZGVzAG1heGltdW1CeXRlcwBHZXRCeXRlcwBzYWx0Qnl0ZXMAaW5wdXRCeXRlcwBrZXlCeXRlcwBnZXRfU2V0dGluZ3MAc2V0X1NldHRpbmdzAHNldHRpbmdzAFNlY3VyZUVxdWFscwBnZXRfQ2hhcnMAUnVudGltZUhlbHBlcnMAQ29uY2F0AFRocm93SW52YWxpZEhhc2hGb3JtYXQAZm9ybWF0AE9iamVjdABCQ3J5cHQuTmV0AGdldF9IYXNoT2Zmc2V0AGdldF9Xb3JrZmFjdG9yT2Zmc2V0AG9mZnNldABHZW5lcmF0ZVNhbHQAc2FsdABCQ3J5cHQAQ29udmVydABCQ3J5cHQuTmV0LU5leHQAU3lzdGVtLlRleHQAQmZDcnlwdENpcGhlcnRleHQAQ3J5cHRSYXcAYnl0ZUFycmF5AEluaXRpYWxpemVBcnJheQBibG9ja0FycmF5AEVLU0tleQBJbml0aWFsaXplS2V5AGN1cnJlbnRLZXkAaW5wdXRLZXkAbmV3S2V5AEVuaGFuY2VkVmVyaWZ5AFN5c3RlbS5TZWN1cml0eS5DcnlwdG9ncmFwaHkAQ29weQBjdXJyZW50S2V5RW5oYW5jZWRFbnRyb3B5AG5ld0tleUVuaGFuY2VkRW50cm9weQBlbmhhbmNlZEVudHJvcHkASXNOdWxsT3JFbXB0eQAAAAAVYwB1AHIAcgBlAG4AdABLAGUAeQAAGUkAbgB2AGEAbABpAGQAIABIAGEAcwBoAAAXYwB1AHIAcgBlAG4AdABIAGEAcwBoAAAtSQBuAHYAYQBsAGkAZAAgAGIAYwByAHkAcAB0ACAAdgBlAHIAcwBpAG8AbgAAL0kAbgB2AGEAbABpAGQAIABiAGMAcgB5AHAAdAAgAHIAZQB2AGkAcwBpAG8AbgAAJ00AaQBzAHMAaQBuAGcAIAB3AG8AcgBrACAAZgBhAGMAdABvAHIAADFXAG8AcgBrACAAZgBhAGMAdABvAHIAIABvAHUAdAAgAG8AZgAgAHIAYQBuAGcAZQAAXUMAdQByAHIAZQBuAHQAIABjAHIAZQBkAGUAbgB0AGkAYQBsAHMAIABjAG8AdQBsAGQAIABuAG8AdAAgAGIAZQAgAGEAdQB0AGgAZQBuAHQAaQBjAGEAdABlAGQAABFpAG4AcAB1AHQASwBlAHkAAFVJAG4AdgBhAGwAaQBkACAAcwBhAGwAdAA6ACAAcwBhAGwAdAAgAGMAYQBuAG4AbwB0ACAAYgBlACAAbgB1AGwAbAAgAG8AcgAgAGUAbQBwAHQAeQAACXMAYQBsAHQAAIDlSQBuAHYAYQBsAGkAZAAgAEgAYQBzAGgAVAB5AHAAZQAsACAAWQBvAHUAIABjAGEAbgAnAHQAIABoAGEAdgBlACAAYQBuACAAZQBuAGgAYQBuAGMAZQBkACAAaABhAHMAaAAgAHcAaQB0AGgAIAB0AHkAcABlACAAbgBvAG4AZQAuACAASABhAHMAaABUAHkAcABlAC4ATgBvAG4AZQAgAGkAcwAgAHUAcwBlAGQAIABmAG8AcgAgAGkAbgB0AGUAcgBuAGEAbAAgAGMAbABhAHIAaQB0AHkAIABvAG4AbAB5AC4AARFoAGEAcwBoAFQAeQBwAGUAAClJAG4AdgBhAGwAaQBkACAAcwBhAGwAdAAgAHYAZQByAHMAaQBvAG4AACtJAG4AdgBhAGwAaQBkACAAcwBhAGwAdAAgAHIAZQB2AGkAcwBpAG8AbgAAJ00AaQBzAHMAaQBuAGcAIABzAGEAbAB0ACAAcgBvAHUAbgBkAHMAADFTAGEAbAB0ACAAcgBvAHUAbgBkAHMAIABvAHUAdAAgAG8AZgAgAHIAYQBuAGcAZQAAAQADAAAABSQAMgAABUQAMgAAFXcAbwByAGsARgBhAGMAdABvAHIAAG9UAGgAZQAgAHcAbwByAGsAIABmAGEAYwB0AG8AcgAgAG0AdQBzAHQAIABiAGUAIABiAGUAdAB3AGUAZQBuACAAewAwAH0AIABhAG4AZAAgAHsAMQB9ACAAKABpAG4AYwBsAHUAcwBpAHYAZQApAABNQgBDAHIAeQBwAHQAIABSAGUAdgBpAHMAaQBvAG4AIABzAGgAbwB1AGwAZAAgAGIAZQAgAGEALAAgAGIALAAgAHgAIABvAHIAIAB5AAAnYgBjAHIAeQBwAHQATQBpAG4AbwByAFIAZQB2AGkAcwBpAG8AbgAAR0UAcgByAG8AcgAgAGgAYQBuAGQAbABpAG4AZwAgAHMAdAByAGkAbgBnACAAaQBuAHQAZQByAHIAbwBnAGEAdABpAG8AbgAAHUkAbgB2AGEAbABpAGQAIABsAGUAbgBnAHQAaAAADWwAZQBuAGcAdABoAAA3SQBuAHYAYQBsAGkAZAAgAG0AYQB4AGkAbQB1AG0AIABiAHkAdABlAHMAIAB2AGEAbAB1AGUAABltAGEAeABpAG0AdQBtAEIAeQB0AGUAcwAAKUIAYQBkACAAbgB1AG0AYgBlAHIAIABvAGYAIAByAG8AdQBuAGQAcwAAH0IAYQBkACAAcwBhAGwAdAAgAEwAZQBuAGcAdABoAAATcwBhAGwAdABCAHkAdABlAHMAAAloAGEAcwBoAAAnSQBuAHYAYQBsAGkAZAAgAEgAYQBzAGgAIABGAG8AcgBtAGEAdAAAAAA8oiyI89JKQZHW9rFetdJlAAQgAQEIAyAAAQUgAQEREQQgAQEOBQcDCAgDBAABAg4FIAIBDg4EIAEDCAUgAg4ICAQAAQYOEAcJCAMIDh0FHQUSCB0FEkkFIAEdBQ4FAAIODg4FIAESSQ4FIAESSQMEIAEODgYgARJJHQMDIAAOCAcDEk0SURJVBAAAEk0GIAEdBR0FBQABDh0FBAAAElEEAAASVQYgAwEOHA4GBwIdBRJJBgADDg4cHAUgAQEdBQMHAQgGBwISEBJZBAcCCAgJBwYIHQMICAgIBAABDQ0LBwgICB0FCAgICAgDIAAIBgcECQkJCQQHAggJCgADARKAnRKAnQgIBwUICB0JCAgJBwYICAgdCQgICgcGCAgdCQgJHQUFIAIBAgIEAAASQQkAAgESgJ0RgKkGIAIBDhJZBAcBEigEIAEOCAUHAhIoCAQgAQIOCLd6XFYZNOCJgKAAJAAABIAAAJQAAAAGAgAAACQAAFJTQTEABAAAAQABAP19O+JLx6zj/j6K9Ae9fGrVVI+ZDC6M98vvy9n4y69LIBwRxEy/fLXNBJJSS1pNDvhoOn+ZEcnXUFVmIUdHXCeV2JaYEY1syQ6/wAfFYI1YEu5EdOzFXzBkro/GiemyJwZCiMbWNgze6cB4BC21LpP+poheEJZqW1dDYgvDdIrtBAsAAAAEEAAAAAQBAAAAAmEAAgAAAgQAAh8ABP////8EAAAAAAQCAAAAAQACBggDBhI9AwYRHAMGEkEDBh0JAwYdAwMGHQgCBg4CBgMCBgYDBhIoAwYRPAMGETgDBhE0AwYRLAMGETAIAAUODg4OCAIOAAkODg4CERwOAhEcCAIFAAIODggEAAEODgcAAw4OCBEcBwADDg4RHAgGAAMODggCCAAEDg4OAhEcCQADHQUdBQMRHAUAAg4IAwUAAgIOCAUAARIQDgMAAA4HAAMCDg4RHAgABAIODgIRHAcAAgIdBR0FBwACHQMdBQgGAAIdBQ4IBAABCAMGIAIBHQkIBwACCR0FEAgHIAIBHQUdBQkgAx0FHQUdBQgDAAABByAEAQ4ODg4EAAEIDgcAAgIOEBIoBAABAgMDKAAOAygACAgBAAgAAAAAAB4BAAEAVAIWV3JhcE5vbkV4Y2VwdGlvblRocm93cwEIAQACAAAAAABHAQAaLk5FVEZyYW1ld29yayxWZXJzaW9uPXY0LjABAFQOFEZyYW1ld29ya0Rpc3BsYXlOYW1lEC5ORVQgRnJhbWV3b3JrIDQuAQApQ2hyaXMgTWNLZWUsIFJ5YW4gRC4gRW1lcmwsIERhbWllbiBNaWxsZXIAAAwBAAdSZWxlYXNlAAA4AQAzMjAwNi0yMDIwIENocmlzIE1jS2VlLCBSeWFuIEQuIEVtZXJsLCBEYW1pZW4gTWlsbGVyAACBRwEAgUFBIGZpeGVkLCBlbmhhbmNlZCBhbmQgbmFtZXNwYWNlIGNvbXBhdGlibGUgdmVyc2lvbiBvZiBCQ3J5cHQuTmV0IHBvcnQgb2YgakJDcnlwdCBpbXBsZW1lbnRlZCBpbiBDIy4gSXQgdXNlcyBhIHZhcmlhbnQgb2YgdGhlIEJsb3dmaXNoIGVuY3J5cHRpb24gYWxnb3JpdGht4oCZcyBrZXlpbmcgc2NoZWR1bGUsIGFuZCBpbnRyb2R1Y2VzIGEgd29yayBmYWN0b3IsIHdoaWNoIGFsbG93cyB5b3UgdG8gZGV0ZXJtaW5lIGhvdyBleHBlbnNpdmUgdGhlIGhhc2ggZnVuY3Rpb24gd2lsbCBiZSwgYWxsb3dpbmcgdGhlIGFsZ29yaXRobSB0byBiZSAiZnV0dXJlLXByb29mIi4AAAwBAAc0LjAuMi4wAAAKAQAFNC4wLjIAABQBAA9CQ3J5cHQuTmV0LU5leHQAAEsBAEZSZXBsYWNlIHdpdGggSGFzaFBhc3N3b3JkLCB0aGlzIG1ldGhvZCB3aWxsIGJlIHJlbW92ZWQgYXQgYSBsYXRlciBkYXRlAAAAAHcpnPDulTnSuS9WO23K3tscLhh6T36s6FfnNHqqbcZrRHi8baPH1jVxXQCdl3+cZilO5Rg5qtwcsQ7bBjmpr1NU1GjC5BNJtkhAGvHRiXWHp0Ou58N+CHwiK+Gt2/cvz9tsrZMkQDsLXZIWwgaucY6HmUt2HwBdaj09KAt/1gEJAAAAAHBGqs4AAU1QAgAAABwBAAAEVgAABDgAAAAAAAAAAAAAAQAAABMAAAAnAAAAIFcAACA5AAAAAAAAAAAAAAABAAERAAAAzg0AAEdXAABHOQAAUlNEU5ieoOzs7rBMrpkkGFQjwlcBAAAAQkNyeXB0Lk5ldC1OZXh0LnBkYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABTSEEyNTYAmJ6g7OzusCxumSQYVCPCV3BGqk5q3OEa+oA9IT0Sk9NNUERCeBcAAI1YCXRU1Rn+38ybN2/2yWTfyEBCEkgYshLCFpIQCJDEmAARhOJk8kgGJjPJvAkwaM0wiQsSlOMGUvGIoj0i4oJSrKJQUdxqKWqrHKtY0VMtWhdKxWLb/7/zCI85tqdzzvfu/e7/3//+97/71LUvqOOAA/qZEa1z6pxrS10lrAAEuA6/PYjc1q5OKjmNuFeP/HqAiAjQhFVz20NBr79bJvmbBgCe9Be3w3HMz6b8vMXz52BqN6ItC/I6X4CMbb/v/jNnvnqiad89eWmLcn/T0Td3z1tko2PnA2MNGmBeTUTYEPmImYjliFJEJmIcQkd2EagOotIHKuMUCLGOgGIOf48rJcNgUGw2ImoQRsXOSY0WPtPwoDVowWbgYTOm2zAtNmphqpGHEUy3Y3rQpIWjJh52m7VwwMzDD5iaLTxUW7TQgCkHei0HdsQwYgRxJ+JexG7EXsTTiOcRRxF9PAf7EZ8jziEsOg6SEdmI8YgViI8RCwUO2hH7ER8gvkf06jm4oAfW5wOiBkowfDMQjej5QcR7iI8QnyG+RJxF/BOhwZ4YsCdLERKi36iDZxGvI04hNph0sBFxM+I2xN0mAT5FfIP4EbnBrIOJiDLENESdmQPqdyzUsXG5xCm5yCuQHlHkWuRdmKcyLXJe0adx51U8NraXuJWN7yWegNDHcTGOG+K4UcVp/E0q/jRHbfJgUfhXcImnYr5e4VbkyyA214nbkO9QuAW5Xal/kPnMg0PVHxvyRIWnqbiB1aUY8pCk8i8hjjtUPA+RqOJVCk9GnqHYT0KeosjHcTGegXwe8hOIZORZivwThTuRF2H+EUQK8jyVv6kqnsjFeD7yZOQ/KvIC5Fm0rlgdHgoV/QmIdOQTFd6OyFDxXwCtcx4mK/wMIgt5pcKLMBmDfLrCb0Pk4Ay4yGlBOFWc9oexKk4xHodRnK6KXy5CXT9Pxan++Dh5fpy8IE5eGCefECefGCcvivO/OM7/SXH+u1Sc9rHJyGconPbJEuSzFP6OwmuQ71P6Vop8tiKnOV2m4nQIlKs4recKFTchKuPqT1Fx8r9Kxcn/qSpO/ler+DQF6vrT4/iMOD4zjtMPNyEseQZod3lcVbKJlRwD2mUmcbS30AzXwftA+wgeg2hhMvNzOjNI649jXw37AtPkFGkqy89n+WaW72M6tSxfwGp9xdpqA1D2FB07GwGWMB0P0yFrWtgZpyOw3ujZGgcIMf3jTH8Ks7mblfex8hmq/MNMZy/TGWQ2h1XSH5k0k7W4l0kHWYtqnSDTSWAWNjCdE0znPNP5dvTLQT7rez53qe/YvkbDalL+Q1EHsROYg5BBVEa8gO3/BcpIgKcUPGXgKQdPBcg9bvB0uUP4HQgGJX+oIxBc0xRwd4Hk9wS6pC7occs9mAQDA/4uWBcIjkravRsk6PKuWgUBhBwYCHqkJsnfHeqBwECobyCkEC+shk5fwLMGPD7JD330kenT6QmG+0LNXn8g2Cat9creAEoDsjdEmTVotA98Qegludq7uW5PCEvWXcoy32SQ3b5QXTgkyeD1Y/OxLBqEVYFgrzsEQSkEfW5Zpk5csWqVjFQOuYMhvEhdpGhByQZiibQ+FMRGsLcoQgvyACad9eQ4ytgI6M7865njI0ML7j45t3P4uYXvifOar/cbljftO/mG/derQxbb8Qk3H0xIrLtp8zrrDdv2pnzfeWXNK/q3E7a2w+ErHtTsgshRT6C3z+uTgpPWSkEWhnLXVFfJpEpXWUllabWrdGpRhae0utJT7sakqkLq8kir3FVTqqoquqrcldXusvLKEslTWbnKDT63v3vA3S1BfS4E+kLeXu8GNwtoUPJJblmC4IAfS6XRpiqwqYqyyhK8gF6sOyqrcpVDl7TK65dgUVttfUNxW0NTQ217Q3FLw6K5bbXNDR1XtC0kUlECG7f0yp5A0OftdHX5fDgBrzm5ayEcLoRXTz57Ydq+GxvveOLsb6+2PPFCe1gOSb2u+kBQUjRtp1Dzfh7eXrzlsKdrZ/2TjmvOtbqO1Cqac3B6KppBppkEtd6p43Y95Gy8/7ovnK/fc/AdRTOmNI2UZlvh8N+7ec/p4oV7X/5H2hv9Xy+5aC7oXodDrijfQ8oRLaRy3098dWVt3cFvDp14ZVZqq6LcMtArBb0eWdH+8CPUPgXwUuPL0uaMW+s3tt5g2rdr2bCi3RaLrasd67h9SuSVqiVnqaoAM19bemfn0r+27K15IaM/edijVL2q16coprI+WuHTbbdsl268c84vn+o9nXDOMaxSbPL6+xXtBz5BbVzdp8/uffLhd4sbbl/7GdcxrPteiKnnxHlWr8w09HCt1yPJWYq8XcIV5g2FXWxqB7qD7r6esEkRLsJVYOaiS7joCi76cy66QzN/mjG2el1+KaSVgx5jHavoapFCBiXrkU3Lo/ujB6JHoi9HjztXTygTi3d0DJ5749i/r6z9i7glcOrMrvlVjfcdWTClULfLR5tVZHjjHotMd5qNr+CNvoIXTZAvhEWo5UU7NAlhK5QbxRSoIkEGrzFBIj+ooc0zS8QzZJkGLyNTSZbIhzUwUQxbYjbaRKyZL+DxWU20SgwbIIcXtbBMCCfDMj5MO39J1LSC3S+iiTXsHhDNnEfplGheB6Wzo67VsbR6A6W10Tm9lOZGm5oie9CL5OhSdLqMWsghp68ip0sFNB7ZTdlcIzo1XoMXusqYjyr/x5D/kc3UgSmjHcgd7cAcpQOGWAdmCWEzJIm46S/hxSSqv1zEexQWGyGbxzOsnq7IuaS/WoMXjGoN3kobNXjVS+ehTsuO0vTo01kCRG7SXFvOTgkO0gUhVlDy3woahbADHEJ/JZ6XldETFgNEbufFQggL4STwUB+LqOOZPEY6l8ceYeul1LqdGsbXCtb6zqKHYrwR4yFVNMQlGCCJD3PQwotm4Ph+FtChBAul44ayBigdGCqyVGEmc6jMIoCZx9dWOY/xsFDOQoEyaIwsiin8oBG0P6/AtkASIEF0R6I4ryYNtViMMIv8qxLC2VCgwRDh61EDZg09P3UwVhBt4NLg3TxFg2476I1UwIsOEDRMGrZBKmpTTQepGC5X0UC2omKKqbBP0pU49LYp4MXYFQ5txD4la5iTWPNKcqaA5kYCH3OhSEBbRVQvneI1y4ifGmqzyIhlFvJjnhGH8VJZFd2RbGStrgEnirWOXWCahw5aVuIdxjl0FB/ETg3eBmw0Hgajg7UzThh0QCHNBXQynRRSya8EHG20mUeCXBJkkSCdBGOkNBHKnW4r5JA1HKVCvIdah86QU3ws8qX8oI0qY/ivHcNjMzKOgdFL/xlkDZ23OMgcs54a+3CacAgfY9ZhEY0ki+h5Eo9RteOLH22uZDbL+MF0HM08mki9aNMos2I7PyiClULtoAAI4VEF6/9U0AFndke24LUydbgMW02kwbjYtPHypmeqm9aNNo29TIRSWkx2miaqNgZGVR3/typnd0cO4ou6bLjbYqFxdUAaPa4rKRKNNEHyaYLUUY5tKDYBA8sEdiEswBgyfHEAsNM42Whia6+dSOPdrQedOeaLjhYKpmmx5VFG7+WVAuZEHsezXwdOuxf7TotIR56iahHfn0yzMRkm0qrIJee068qUSJusV9NtOxJpM5hhSQoYBV7APZvj7ZCh5aNGSNHzZki18kmgxXPDWcfOitqBUA/e4bwediw2rPdIfex8VB8UN//ZeXr+8x+MHTz0zmePffnDoa/f+tO3dxw+cPTq7gsPagNnMt/fnU5voHyzgSYiew9Zkmx6zA9QPjvbJlL+4rE3x+vu9gfkEJ3g9XhprfW7fWHZK2u5TYscjXizne+PXQ7j/di03hm96fxA85v7D+TUVXx3oNV+vr7lsbOPX3jqOu76hJ1/WL3+WA62tzwB/UjiRT2NrR7S6OOgYcH5TbdwPmscJeasAsbGjmVsbD5j+XmM5U9grCgmK8rPjPPrpwN1i9157bHFaz/mhSNbZu2uX/Bh8nvyjvmL9F8kZ/8qODV1fccVH1NAxlpVgUqZToHKpj9BsnMWU6Be9FqotVZ3UJaCl9u/3nno0OIL1WmThembH/32rjF7N0xZ8bfXz5qOcAtmbDnGm596zW7Dp4UZd9Z0XtTxLXiU4nO1IEMpgPE0eWfwENmO21JCPh6NLjq7iuissAp4+FpoAWYKtHWNUpuI2znOOysYeJyd2RRQ2l5pmWbQHmvlFVWuRQznqWpeLgWrqGETOZ8ftKqKtetmsNlvALOjAwOudfXgmQJ8Wz8lkLeBJRWDFgqYX28wgR8XAV3+WYx+eiw2P+AUXq3Z8dz2mqyHTI+8uetxX/eBF9977aHo4QkTdrxSa7xv0x4yl2lQjYVdNWnTYpPWiXlXZBg9GEMzagIdA+MpFDn0wRlF2zsfGSmMpbcWxdKtCr99fMqlS5ir2e31t7o9a/A6rw10rta3xa7/OryvVZSUuOgCH3T3SvSKKl4Su+7PXFvhKnHVyrLU2+kL14ZCQW/nAL6hsK8JSl9HFoy4R6SR3hHZ+fBtt+TWlPxuXpU38GzznrNN+9dNmv1CytDGfT9sXfrU288/Ok7ljOLIqG2a3T9l9Y/OWxd9/tI2YeP5e2/J1LZZSj45eeLoDRnn3510w8+aclKf1c8z0XRdFO6TLhuALZOcx74busbSXbr/QdfbK07p1szalDhv612/n3Hfc0nOc9lrmjHO/wE9ZQAAAAAAAAAAAABXZQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASWUAAAAAAAAAAAAAAABfQ29yRGxsTWFpbgBtc2NvcmVlLmRsbAAAAAAAAAAA/yUAIAAQpgsx0ay135jbcv0vt98a0O2v4biWfiZqRZB8upl/LPFHmaEk92yRs+LyAQgW/I6F2CBpY2lOV3Gj/likfj2T9I90lQ1Yto5yWM2Lce5KFYIdpFR7tVlawjnVMJwTYPIqI7DRxfCFYCgYeUHK7zjbuLDceY4OGDpgiw6ebD6KHrDBdxXXJ0sxvdovr3hgXGBV8yVV5pSrVapimEhXQBToY2o5ylW2EKsqNFzMtM7oQRGvhlShk+lyfBEU7rMqvG9jXcWpK/YxGHQWPlzOHpOHmzO61q9czyRsgVMyeneGlSiYSI87r7lLaxvov8STIShmzAnYYZGpIftgrHxIMoDsXV1dhO+xdYXpAiMm3IgbZeuBPokjxayW0/NvbQ85QvSDgkQLLgQghKRK8MhpXpsfnkJoxiGabOn2YZwMZ/CI06vSoFFqaC9U2CinD5ajM1GrbAvvbuQ7ehNQ8Du6mCr7fh1l8aF2Aa85PlnKZogOQ4IZhu6MtJ9vRcOlhH2+Xos72HVv4HMgwYWfRBpApmrBVmKq004Gdz82ct/+Gz0Cm0Ik19A3SBIK0NPqD9ubwPFJyXJTB3sbmYDYedQl997o9hpQ/uM7THm2veBsl7oGwAS2T6nBxGCfQMKeXF5jJGoZr2/7aLVTbD7rsjkTb+xSOx9R/G0slTCbREWBzAm9Xq8E0OO+/Uoz3gcoD2azSy4ZV6jLwA90yEU5XwvS2/vTub3AeVUKMmAaxgCh1nlyLED+JZ9nzKMf+/jppY74IjLb3xZ1PBVrYf3IHlAvq1IFrfq1PTJghyP9SHsxU4LfAD67V1yeoIxvyi5WhxrbaRff9qhC1cP/fijGMmesc1VPjLAnW2nIWMq7XaP/4aAR8LiYPfoQuIMh/Wy1/Epb09EteeRTmmVF+La8SY7SkJf7S9ry3eEzfsukQRP7YujG5M7ayiDvAUx3Nv6eftC0H/ErTdrblZiRkK5xjq3qoNWTa9DRjtDgJcevL1s8jreUdY774vaPZCsS8hK4iIgc8A2QoF6tTxzDj2iR8c/RrcGosxgiLy93Fw6+/i116qEfAosPzKDl6HRvtdbzrBiZ4onO4E+otLfgE/2BO8R82ait0maiXxYFd5WAFHPMk3cUGiFlIK3mhvq1d/VCVMfPNZ37DK/N66CJPnvTG0HWSX4eri0OJQBes3EguwBoIq/guFebNmQkHrkJ8B2RY1Wqpt9ZiUPBeH9TWtmiW30gxbnlAnYDJoOpz5ViaBnIEUFKc07KLUezSqkUe1IAURsVKVOaP1cP1uTGm7x2pGArAHTmgbVvuggf6RtXa+yW8hXZDSohZWO2tvm55y4FNP9kVoXFXS2wU6GPn6mZR7oIageFbulwektEKbO1Lgl12yMmGcSwpm6tfd+nSbhg7pxmsu2PcYyq7P8XmmlsUmRW4Z6xwqUCNhkpTAl1QBNZoD46GOSamFQ/ZZ1CW9bkj2vWP/eZB5zSofUw6O/mOC1NwV0l8IYg3Uwm63CExumCY17MHgI/a2gJye+6PhQYlzyhcGprhDV/aIbioFIFU5y3NwdQqhyEBz5crt5/7ER9jrjyFlc32jqwDQxQ8AQfHPD/swACGvUMrrJ0tTxYeoMlvSEJ3PkTkdH2L6l8c0cylAFH9SKB5eU63NrCNzR2tcin3fOaRmFEqQ4D0A8+x8jsQR51pJnNOOIvDuo7obuAMjGzPhg4i1ROCLltTwMNQm+/BAr2kBK4LHl8lyRysHlWr4mvvB93mt4QCJPZEq6Lsy4/z9wfchJVJHFrLubdGlCHzYSfGEdYehfaCHS8mp+8jH1L6Trseuz6HYXbZkMJY9LDZMRHGBzvCNkVMjc7Q90WusIkQ02hElHEZSoCAJRQ3eQ6E57433FVTjEQ1nesgZsZEV/xVjUEa8ej1zsYETwJpSRZ7eaP8vr78Zcsv7qebjwVHnBF44axb+nqCl4OhrMqPloc5x93+gY9TrncZSkPHeeZ1ok+gCXIZlJ4yUwuarMQnLoOFcZ46uKUUzz8pfQtCh6nTvfyPSsdNg8mORlgecIZCKcjUrYSE/du/q3rZh/D6pVFvOODyHum0Td/sSj/jAHv3TLDpVpsvoUhWGUCmKtoD6XO7juVL9utfe8qhC9uWyi2IRVwYQcpdUfd7BAVn2EwqMwTlr1h6x7+NAPPYwOqkFxztTmicEwLnp7VFN6qy7yGzO6nLGJgq1yrnG6E87KvHotkyvC9GblpI6BQu1plMlpoQLO0KjzV6Z4x97ghwBkLVJuZoF+Hfpn3lah9PWKaiDf4dy3jl1+T7RGBEmgWKYg1DtYf5seh396WmbpYeKWE9VdjciIb/8ODm5ZGwhrrCrPNVDAuU+RI2Y8oMbxt7/LrWOr/xjRh7Sj+czx87tkUSl3jt2ToFF0QQuATPiC24u5F6quqoxVPbNvQT8v6QvRCx7W7au8dO09lBSHNQZ55HtjHTYWGakdL5FBigT3yoWLPRiaNW6CDiPyjtsfBwyQVf5J0y2kLioRHhbKSVgC/WwmdSBmtdLFiFAAOgiMqjUJY6vVVDD70rR1hcD8jkvByM0F+k43x7F/W2zsibFk33nxgdO7Lp/KFQG4yd86EgAemnlD4GVXY7+g1l9lhqqdpqcIGDMX8qwRa3MoLgC56RJ6ENEXDBWfV/cmeHg7T23PbzYhVEHnaX2dAQ2fjZTTExdg4PnGe+Cg9IP9t8echPhVKPbCPK5/j5vetg9toWj3p90CBlBwmTPY0KWmU9yAVQffUAnYua/S8aACi1HEkCNRq9CAzt9S3Q69hAFAu9jkeRkUkl3RPIRRAiIu/HfyVTa+RtZbT3fRwRS+gZuwJvL+Fl70D0G2sfwSFyzGzJ+uWQTn9VeZHJdqaCsqrJXhQKPQpBFPahiwK+2226WIU3GgAaUjXpMAOaO6NoSei/j9PjK2H6AbgjLW21vR6fB7OquxfN9OZo3jOQiprQDWe/iC5hfPZq9c57otOEjv3+skdVhhtSzFmoyayl+PqdPpuOjJDW93350Fo+yB4yk71CvuXs/7YrFZARSeVSLo6OlNVh42DILepa/5LlZbQvGeoVViaFaFjKanMM9vhmVZKKqb5JTE/HH70XnwxKZAC6Pj9cC8nBFwVu4DjLCgFSBXBlSJtxuQ/E8FI3IYPx+7J+QcPHwRBpHlHQBduiF3rUV8y0cCb1Y/BvPJkNRFBNHh7JWCcKmCj6PjfG2xjH8K0Eg6eMuEC0U9mrxWB0crglSNr4ZI+M2ILJDsiub7uDqKyhZkNuuaMDHLeKPeiLUV4EtD9lLeVYgh9ZPD1zOdvo0lU+kh9hyf9ncMejT7zQWNHCnT/Lpmrbm86N/349GDcEqj43euhTOEbmQ1rbtsQVXvGNyxnbTvUZScE6NDcxw0p8aP/AMySDzm1C+0Pafufe2acfdvOC8+RoKNeFdmILxO7JK1bUb95lHvr1jt2sy45N3lZEcyX4iaALTEu9KetQmg7K2rGzEx1EhzxLng3QhJq51GSt+a7oQZQY/tLGBBrGvrtyhHYvSU9ycPh4lkWQkSGExIKbuwM2Srqq9VOZ69kX6iG2ojpv77+w+RkV4C8nYbA9/D4e3hgTWADYEaD/dGwHzj2BK5Fd8z8Ntcza0KDcase8IdBgLBfXgA8vlegdySu6L2ZQkZVYS5Yv4/0WE6i/d3yOO909MK9iYfD+WZTdI6zyFXydbS52fxGYSbreoTfHYt5DmqE4pVfkY5ZbkZwV7QgkVXVjEzeAsnhrAu50AWCu0hiqBGeqXR1thl/twncqeChCS1mM0YyxAIfWuiMvvAJJaCZShD+bh0dPbka36SlCw/yhqFp8Wgog9q33P4GOVebzuKhUn/NTwFeEVD6gwanxLUCoCfQ5g0njPiaQYY/dwZMYMO1BqhhKHoX8OCG9cCqWGAAYn3cMNee5hFj6jgjlN3CUzQWwsJW7su73ra8kKF9/Ot2HVnOCeQFb4gBfEs9CnI5JHySfF9y44a5nU1ytFvBGvy4ntN4VVTttaX8CNN8PdjED61NXu9QHvjmYbHZFIWiPBNRbOfH1W/ETuFWzr8qNjfIxt00MprXEoJjko76DmfgAGBAN845Os/1+tM3d8KrGy3FWp5nsFxCN6NPQCeC076bvJmdjhHVFXMPv34cLdZ7xADHaxuMt0WQoSG+sW6ytG42ai+rSFd5bpS80najxsjCSWXu+A9Tfd6NRh0Kc9XGTdBM27s5KVBGuqnoJpWsBONevvDV+qGaUS1q4ozvYyLuhpq4wonA9i4kQ6oDHqWk0PKcumHAg01q6ZtQFeWP1ltkuvmiJijhOjqnhpWpS+liVe/T7y/H2vdS92lvBD9ZCvp3FankgAGGsIet5gmbk+U+O1r9kOmX1zSe2bfwLFGLKwI6rNWWfaZ9AdY+z9EoLX18zyWfH5u48q1ytNZaTPWIWnGsKeDmpRng/aywR5v6k+2NxNPozFc7KClm1fgoLhN5kQFfeFVgde1EDpb3jF7T49RtBRW6bfSIJWGhA73wZAUVnuvDoleQPOwaJ5cqBzqpm20/G/UhYx77Zpz1GfPcJijZM3X1/VWxgjRWA7s8uooRd1Eo+NkKwmdRzKtfkq3MURfoTY7cMDhiWJ03kfkgk8KQeurOez77ZM4hUTK+T3d+47aoRj0pw2lT3kiA5hNkEAiuoiSybd39LYVpZiEHCQpGmrPdwEVkz95sWK7IIBzd975bQI1YG38B0sy747Rrfmqi3UX/WTpECjU+1c20vKjO6nK7hGT6rhJmjUdvPL9j5JvSnl0vVBt3wq5wY072jQ0OdFcTW+dxFnL4XX1TrwjLQEDM4rROakbSNISvFQEoBLDhHTqYlbSfuAZIoG7Ogjs/b4KrIDVLHRoB+CdyJ7FgFWHcP5PnK3k6u70lRTThOYigS3nOUbfJMi/Juh+gfsgc4PbRx7zDEQHPx6rooUmHkBqavU/Uy97a0DjaCtUqwzkDZzaRxnwx+Y1PK7Hgt1me9zq79UP/GdXynEXZJywil78q/OYVcfyRDyUVlJthk+X665y2zllkqMLRqLoSXgfBtgxqBeNlUNIQQqQDyw5u7OA725gWvqCYTGTpeDIylR+f35LT4Cs0oNMe8nGJQXQKG4w0o0sgcb7F2DJ2w42fNd8uL5mbR28L5h3x4w9U2kzlkdjaHs95Ys5vfj7NZrEYFgUdLP3F0o+EmSL79lfzI/UjdjKmMTWokwLNzFZigfCstet1Wpc2Fm7Mc9KIkmKW3tBJuYEbkFBMFFbGcb3HxuYKFHoyBtDhRZp78sP9U6rJAA+oYuK/Jbv20r01BWkScSICBLJ8z8u2K5x2zcA+EVPT40AWYL2rOPCtRyWcIDi6ds5G98Whr3dgYHUgTv7LhdiN6Iqw+ap6fqr5TFzCSBmMivsC5GrDAfnh69Zp+NSQoN5cpi0lCT+f5gjCMmFOt1vid87j349X5nLDOv////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8AAAAAAQAAADYAAAA3AAAAOAAAADkAAAA6AAAAOwAAADwAAAA9AAAAPgAAAD8AAAD/////////////////////////////////////AgAAAAMAAAAEAAAABQAAAAYAAAAHAAAACAAAAAkAAAAKAAAACwAAAAwAAAANAAAADgAAAA8AAAAQAAAAEQAAABIAAAATAAAAFAAAABUAAAAWAAAAFwAAABgAAAAZAAAAGgAAABsAAAD///////////////////////////////8cAAAAHQAAAB4AAAAfAAAAIAAAACEAAAAiAAAAIwAAACQAAAAlAAAAJgAAACcAAAAoAAAAKQAAACoAAAArAAAALAAAAC0AAAAuAAAALwAAADAAAAAxAAAAMgAAADMAAAA0AAAANQAAAP//////////////////////////LgAvAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkAWgBhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHoAMAAxADIAMwA0ADUANgA3ADgAOQBocHJPQm5hZWxvaGVTcmVkRHlyY3RidW+Iaj8k0wijhS6KGRNEc3ADIjgJpNAxnymY+i4IiWxO7OYhKEV3E9A4z2ZUvmwM6TS3KazA3VB8ybXVhD8XCUe12dUWkhv7eYkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAEAAAABgAAIAAAAAAAAAAAAAAAAAAAAEAAQAAADAAAIAAAAAAAAAAAAAAAAAAAAEAAAAAAEgAAABYgAAALAYAAAAAAAAAAAAALAY0AAAAVgBTAF8AVgBFAFIAUwBJAE8ATgBfAEkATgBGAE8AAAAAAL0E7/4AAAEAAAAEAAAAAgAAAAQAAAACAD8AAAAAAAAABAAAAAIAAAAAAAAAAAAAAAAAAABEAAAAAQBWAGEAcgBGAGkAbABlAEkAbgBmAG8AAAAAACQABAAAAFQAcgBhAG4AcwBsAGEAdABpAG8AbgAAAAAAAACwBIwFAAABAFMAdAByAGkAbgBnAEYAaQBsAGUASQBuAGYAbwAAAGgFAAABADAAMAAwADAAMAA0AGIAMAAAAJgCQAEBAEMAbwBtAG0AZQBuAHQAcwAAAEEAIABmAGkAeABlAGQALAAgAGUAbgBoAGEAbgBjAGUAZAAgAGEAbgBkACAAbgBhAG0AZQBzAHAAYQBjAGUAIABjAG8AbQBwAGEAdABpAGIAbABlACAAdgBlAHIAcwBpAG8AbgAgAG8AZgAgAEIAQwByAHkAcAB0AC4ATgBlAHQAIABwAG8AcgB0ACAAbwBmACAAagBCAEMAcgB5AHAAdAAgAGkAbQBwAGwAZQBtAGUAbgB0AGUAZAAgAGkAbgAgAEMAIwAuACAASQB0ACAAdQBzAGUAcwAgAGEAIAB2AGEAcgBpAGEAbgB0ACAAbwBmACAAdABoAGUAIABCAGwAbwB3AGYAaQBzAGgAIABlAG4AYwByAHkAcAB0AGkAbwBuACAAYQBsAGcAbwByAGkAdABoAG0AGSBzACAAawBlAHkAaQBuAGcAIABzAGMAaABlAGQAdQBsAGUALAAgAGEAbgBkACAAaQBuAHQAcgBvAGQAdQBjAGUAcwAgAGEAIAB3AG8AcgBrACAAZgBhAGMAdABvAHIALAAgAHcAaABpAGMAaAAgAGEAbABsAG8AdwBzACAAeQBvAHUAIAB0AG8AIABkAGUAdABlAHIAbQBpAG4AZQAgAGgAbwB3ACAAZQB4AHAAZQBuAHMAaQB2AGUAIAB0AGgAZQAgAGgAYQBzAGgAIABmAHUAbgBjAHQAaQBvAG4AIAB3AGkAbABsACAAYgBlACwAIABhAGwAbABvAHcAaQBuAGcAIAB0AGgAZQAgAGEAbABnAG8AcgBpAHQAaABtACAAdABvACAAYgBlACAAIgBmAHUAdAB1AHIAZQAtAHAAcgBvAG8AZgAiAC4AAAB0ACoAAQBDAG8AbQBwAGEAbgB5AE4AYQBtAGUAAAAAAEMAaAByAGkAcwAgAE0AYwBLAGUAZQAsACAAUgB5AGEAbgAgAEQALgAgAEUAbQBlAHIAbAAsACAARABhAG0AaQBlAG4AIABNAGkAbABsAGUAcgAAAEgAEAABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABCAEMAcgB5AHAAdAAuAE4AZQB0AC0ATgBlAHgAdAAAADAACAABAEYAaQBsAGUAVgBlAHIAcwBpAG8AbgAAAAAANAAuADAALgAyAC4AMAAAAEgAFAABAEkAbgB0AGUAcgBuAGEAbABOAGEAbQBlAAAAQgBDAHIAeQBwAHQALgBOAGUAdAAtAE4AZQB4AHQALgBkAGwAbAAAAIwANAABAEwAZQBnAGEAbABDAG8AcAB5AHIAaQBnAGgAdAAAADIAMAAwADYALQAyADAAMgAwACAAQwBoAHIAaQBzACAATQBjAEsAZQBlACwAIABSAHkAYQBuACAARAAuACAARQBtAGUAcgBsACwAIABEAGEAbQBpAGUAbgAgAE0AaQBsAGwAZQByAAAAUAAUAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0AZQAAAEIAQwByAHkAcAB0AC4ATgBlAHQALQBOAGUAeAB0AC4AZABsAGwAAABAABAAAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAEIAQwByAHkAcAB0AC4ATgBlAHQALQBOAGUAeAB0AAAAMAAGAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAANAAuADAALgAyAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADQALgAwAC4AMgAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAMAAAAbDUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
"@
        $dllBytes = [Convert]::FromBase64String($base64Dll)
        [System.IO.File]::WriteAllBytes($bcryptDllPath, $dllBytes)

        Write-LogMessage "BCrypt.Net DLL extracted to $bcryptDllPath" White
    }
    else {
        Write-LogMessage "BCrypt.Net DLL is already present at $bcryptDllPath" Green
    }
}
function Invoke-Key {
    return [System.IO.File]::ReadAllBytes($keyFile)
}

function Import-KeyUserBinary {
    # Generate the current timestamp
    $timestamp = [math]::Floor([double]::Parse((Get-Date -UFormat %s))).ToString()


    # Convert the timestamp and secret key to UTF-8 byte arrays
    $data = [Text.Encoding]::UTF8.GetBytes($timestamp)
    $key = [Text.Encoding]::UTF8.GetBytes($secretKey)

    # Create HMAC-SHA256 object and compute the hash
    $hmacsha256 = New-Object System.Security.Cryptography.HMACSHA256
    $hmacsha256.Key = $key
    $hashBytes = $hmacsha256.ComputeHash($data)

    # Convert the hash to a hexadecimal string
    $hash = -join ($hashBytes | ForEach-Object { "{0:x2}" -f $_ })

    # Prepare the headers and JSON body
    $headers = @{"Content-Type" = "application/json" }
    $jsonBody = @{"signature" = $hash; "timestamp" = $timestamp } | ConvertTo-Json
    $wolurl = "http://${wolip}:${wolport}"

    try {
        # Invoke the REST method
        $response = Invoke-RestMethod -Uri "$wolurl/api/sync_encryption_key" -Method Post -Headers $headers -Body $jsonBody

        # Check if the response contains a success message
        if ($response.success -eq $true) {
            $encryptionKeyBase64 = $response.encryption_key

            if ($encryptionKeyBase64) {
                # Decode the Base64-encoded encryption key back to binary
                $encryptionKeyBinary = [Convert]::FromBase64String($encryptionKeyBase64)

                # Save the binary key to a file named enc.bin
                [System.IO.File]::WriteAllBytes($keyFile, $encryptionKeyBinary)

                Write-LogMessage "Encryption key sync complete $keyFile" Green
            }
            else {
                Write-LogMessage "❌ Error: Failed to retrieve the encryption key from the server response." Red
                exit 1
            }
        }
        else {
            Write-LogMessage "❌ Error: ${response.message}" Red
            exit 1
        }
    }
    catch {
        Write-LogMessage "❌ Error: $_" Red
        exit 1
    }
}

function Import-BcryptDll {
    Restore-BcryptDll
    Add-Type -Path $bcryptDllPath
}

function Start-TcpServer {
    try {
        $global:listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Parse($ipAddress), $port)
        $listener.Start()
        Write-LogMessage "Server started on $($ipAddress):$port" Green

        while ($true) {
            if ($listener.Pending()) {
                $client = $listener.AcceptTcpClient()
                $stream = $client.GetStream()
                $reader = [System.IO.StreamReader]::new($stream)
                $writer = [System.IO.StreamWriter]::new($stream)
                $writer.AutoFlush = $true

                $data = $reader.ReadLine()

                Invoke-ClientRequest -data $data -writer $writer

                $client.Close()
            }
            Start-Sleep -Milliseconds 100
        }
    }
    catch {
        Write-LogMessage "An error occurred: $_"
    }
    finally {
        if ($null -ne $listener) {
            $listener.Stop()
            Write-LogMessage "Server stopped" White
        }
    }
}

function ConvertFrom-Encrypt {
    param (
        [string]$encryptedData
    )

    try {
        $encryptedBytes = [Convert]::FromBase64String($encryptedData)
        $iv = $encryptedBytes[0..15]
        $cipherText = $encryptedBytes[16..($encryptedBytes.Length - 1)]

        $aes = New-Object System.Security.Cryptography.AesManaged
        $aes.Key = Invoke-Key
        $aes.IV = $iv
        $aes.Mode = [System.Security.Cryptography.CipherMode]::CBC
        $aes.Padding = [System.Security.Cryptography.PaddingMode]::PKCS7

        $decryptor = $aes.CreateDecryptor()
        $decryptedBytes = $decryptor.TransformFinalBlock($cipherText, 0, $cipherText.Length)

        # Return the decrypted string
        return [System.Text.Encoding]::UTF8.GetString($decryptedBytes)
    }
    catch {
        # Log the decryption error and return $null
        Write-LogMessage "Decryption error: $_"
        $writer.Write("Decryption error: $_")
        return $null
    }
}

function Invoke-ClientRequest {
    param (
        [string]$data,
        [System.IO.StreamWriter]$writer
    )

    try {
        Write-LogMessage "Data recieved : $data"
        $decryptedData = ConvertFrom-Encrypt -encryptedData $data
        $parts = $decryptedData -split '\|'
        if ($parts.Length -eq 3) {
            $username, $password, $command = $parts

            if ($global:users.PSObject.Properties.Name -contains $username) {
                $user = $global:users.$username

                try {
                    $passwordValid = [BCrypt.Net.BCrypt]::Verify($password, $user.password_hash)
                }
                catch {
                    Write-LogMessage "Error during password verification: $_"
                    $writer.WriteLine("Error during password verification")
                    return
                }

                if ($passwordValid) {
                    switch ($command.ToLower()) {
                        "shutdown" {
                            $writer.WriteLine("Shutdown command received")
                            Stop-Computer -Force
                            Write-LogMessage "Shutdown command invoked by '$username'. Server will continue running." White
                        }
                        default {
                            $writer.WriteLine("Invalid command")
                            Write-LogMessage "Invalid command received: $command" White
                        }
                    }
                }
                else {
                    $writer.WriteLine("Invalid credentials")
                    Write-LogMessage "Invalid credentials provided by client. Username: '$username'"
                }
            }
            else {
                $writer.WriteLine("User not found")
                Write-LogMessage "User '$username' not found in the users list."
            }
        }
        else {
            $writer.WriteLine("Invalid format")
            Write-LogMessage "Invalid data format received."
        }
    }
    catch {
        Write-LogMessage "Error during decryption or processing: $_"
        $writer.WriteLine("Error during decryption or processing")
    }
}

function Stop-TcpServer {
    if ($null -ne $listener) {
        $listener.Stop()
        Write-LogMessage "Server stopped by user." White
    }
}

$null = Register-EngineEvent -SourceIdentifier ConsoleBreak -Action {
    Write-LogMessage "Ctrl+C detected, stopping the server..." White
    Stop-TcpServer
    Exit
}

Import-BcryptDll
Initialize-Users
Import-KeyUserBinary
Start-TcpServer