name: Zip and Release Python/wol Directory

on:
  push:
    branches:
      - main
    paths:
      - 'Python/wol/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  zip_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip the Python/wol directory
      run: |
        zip -r python_wol.zip Python/wol/

    - name: Get latest tag and create a new version tag
      id: new_tag
      run: |
        # Get the latest tag or use v0.0.0 if none exists
        LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        # Extract major, minor, and patch
        IFS='.' read -r -a VERSION_PARTS <<< "${LATEST_TAG/v/}"
        MAJOR=${VERSION_PARTS[0]}
        MINOR=${VERSION_PARTS[1]}
        PATCH=${VERSION_PARTS[2]}
        # Increment patch version
        NEW_TAG="v$MAJOR.$MINOR.$((PATCH+1))"
        echo "::set-output name=NEW_TAG::$NEW_TAG"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.new_tag.outputs.NEW_TAG }}
        release_name: Release ${{ steps.new_tag.outputs.NEW_TAG }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./python_wol.zip
        asset_name: python_wol.zip
        asset_content_type: application/zip